import type { Vehicle } from "@/lib/inventory/types";
import type { VehicleFormValues } from "@/lib/inventory/schema";

// テストサポート: `vehicles` テーブルの最小限の妥当なレコード／PATCHペイロードを組み立てる。
// 個々のテストは `overrides` で差分だけを指定すればよい。

const NIL_UUID = "00000000-0000-0000-0000-000000000000";

export function buildVehicleRecord(overrides: Partial<Vehicle> = {}): Vehicle {
  return {
    id: NIL_UUID,
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
    deleted_at: null,
    manufacturer_id: NIL_UUID,
    model_id: NIL_UUID,
    series_id: null,
    generation_id: null,
    grade_id: null,
    status: "published",
    is_recommended: false,
    is_new_arrival: false,
    price: 5_000_000,
    total_price: null,
    engine: null,
    engine_model_code: null,
    displacement_cc: null,
    horsepower: null,
    torque: null,
    transmission: null,
    drivetrain: null,
    body_type: null,
    model_year: null,
    registration_year: null,
    mileage_km: null,
    shaken_expiry: null,
    owner_count: null,
    indoor_storage: null,
    accident_history: null,
    interior_color: null,
    exterior_color: null,
    seat_material: null,
    vin: null,
    sales_comment: null,
    manager_comment: null,
    story: null,
    sourcing_background: null,
    appeal_points: null,
    engine_features: null,
    common_issues: null,
    maintenance_cost: null,
    purchase_notes: null,
    recommended_points: null,
    maintenance_details: null,
    custom_details: null,
    other_notes: null,
    display_order: 0,
    scheduled_publish_at: null,
    ...overrides,
  };
}

// vehicleFormSchema（lib/inventory/schema.ts）を満たすPATCHリクエストボディの最小構成。
export function buildPatchPayload(
  overrides: Partial<VehicleFormValues> = {},
): VehicleFormValues {
  return {
    related: [],
    tags: [],
    manufacturer_id: NIL_UUID,
    model_id: NIL_UUID,
    series_id: null,
    generation_id: null,
    grade_id: null,
    status: "published",
    is_recommended: false,
    is_new_arrival: false,
    price: 5_000_000,
    total_price: null,
    engine: null,
    engine_model_code: null,
    displacement_cc: null,
    horsepower: null,
    torque: null,
    transmission: null,
    drivetrain: null,
    body_type: null,
    model_year: null,
    registration_year: null,
    mileage_km: null,
    shaken_expiry: null,
    owner_count: null,
    indoor_storage: null,
    accident_history: null,
    interior_color: null,
    exterior_color: null,
    seat_material: null,
    vin: null,
    sales_comment: null,
    manager_comment: null,
    story: null,
    sourcing_background: null,
    appeal_points: null,
    engine_features: null,
    common_issues: null,
    maintenance_cost: null,
    purchase_notes: null,
    recommended_points: null,
    maintenance_details: null,
    custom_details: null,
    other_notes: null,
    scheduled_publish_at: null,
    ...overrides,
  };
}
